### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by shanyi15**

### CODE REVIEW

**Comment by varunarora** [comment]
Hhaa I was just about to approve @shanyi15

**Comment by shanyi15** [comment]
Thank ~its too urgent, forgive me : p

**Comment by varunarora** [comment]
We need to merge this into `develop` too (apart from the fact that merging into master directly is dangerous!). Can you please create a duplicate PR for `develop`? I am restoring the branch.

**Comment by shanyi15** [comment]
Yeah I have done that, please turn to the closed pr

**Comment by varunarora** [comment]
Ahaa! Got it.

**Comment by varunarora** [comment]
We usually don't merge feature branch into master. It's always feature branch -> develop -> master. But this time it is urgent, so no problem :)

**Pull request merged**
